- id: cargo-fmt
  name: cargo fmt
  description: Format Rust code according to style guidelines.
  language: rust
  files: \.rs$
  pass_filenames: false
  entry: cargo fmt
  args: ["--all"]

- id: cargo-update
  name: cargo update
  description: Update dependencies in the Cargo.lock file.
  language: rust
  files: (Cargo.(toml|lock))
  pass_filenames: false
  entry: cargo-update-shim
  args: ["--workspace"]

- id: cargo-clippy
  name: cargo clippy
  description: Catch common mistakes and improve Rust code with a collection of lints.
  language: rust
  files: (Cargo.(toml|lock)|\.rs$)
  pass_filenames: false
  entry: cargo clippy
  args: ["--workspace"]

- id: cargo-check
  name: cargo check
  description: Check Rust code for compilation errors.
  language: rust
  files: (Cargo.(toml|lock)|\.rs$)
  pass_filenames: false
  entry: cargo check
  args: ["--workspace"]

- id: cargo-test
  name: cargo test
  description: Execute unit and integration tests of Rust code.
  language: rust
  files: (Cargo.(toml|lock)|\.rs$)
  pass_filenames: false
  entry: cargo test
  args: ["--workspace"]

- id: cargo-test-doc
  name: cargo test --doc
  description: Execute documentation tests of Rust code.
  language: rust
  files: (Cargo.(toml|lock)|\.rs$)
  pass_filenames: false
  entry: cargo test --doc
  args: ["--workspace"]

- id: cargo-doc
  name: cargo doc
  description: Build the documentation of Rust code.
  language: rust
  files: (Cargo.(toml|lock)|\.rs$|^README\.)
  pass_filenames: false
  entry: cargo doc
  args: ["--workspace"]

- id: cargo-miri-test
  name: cargo miri test
  description: Detect undefined behavior in Rust tests (requires nightly toolchain).
  language: rust
  files: (Cargo.(toml|lock)|\.rs$|^README\.)
  pass_filenames: false
  entry: cargo +nightly miri test
  args: ["--workspace"]

- id: cargo-miri-run
  name: cargo miri run
  description: Detect undefined behavior in Rust binary (requires nightly toolchain).
  language: rust
  files: (Cargo.(toml|lock)|\.rs$|^README\.)
  pass_filenames: false
  entry: cargo +nightly miri run

- id: cargo-deny-check
  name: cargo deny check
  description: Lint Rust depencencies.
  language: rust
  files: (Cargo.(toml|lock)|\.rs$|^README\.)
  pass_filenames: false
  entry: cargo deny check

- id: cargo-fix
  name: cargo fix
  description: Apply Rust code fixes
  language: rust
  files: \.rs$
  pass_filenames: false
  entry: cargo fix
  args: ["--workspace", "--allow-dirty", "--allow-staged"]
